### ISSUE TITLE
Add an option to specify custom dictionary files

### ISSUE THREAD

**Issue by balta2ar** [ujihisa/neco-look#18]
As discussed with @Shougo, could you please support an option to specify several custom dictionary files (look can be invoked with several files as input)?

Additionally, it could be nice to have an option for look's `--ignore-case` argument.

Thank you.

**Comment by Shougo** [comment]
I don't want to add the option.
You should use dictionary source instead.
Why you does not use dictionary source?
Please describe it.

**Comment by balta2ar** [comment]
`man look` says:
> As look performs a binary search, the lines in file must be sorted

Considering this, I think `look` does filtering faster, than deoplete on Python.

Besides, because this plugin in a wrapper for look, it's natural to support look's options in the plugin. It's not many of them and they aren't likely to ever change.

**Comment by Shougo** [comment]
https://github.com/ujihisa/neco-look/pull/17

Please see it.

**Comment by Shougo** [comment]
I don't want to add the options.
Because neco-look includes the other plugin sources(neocomplcache, neocomplete, deoplete).
I don't want to touch them.

**Comment by balta2ar** [comment]
Thanks, I configured `dictionary` in deoplete and it works. I didn't do any exact measurements, but I still feel that deoplete pops up completion menu **slower** than `look`. And it is no wonder, because deoplete scans through the whole dictionary, right? If not, I think there could be a special mode to lookup words from dictionary using binary search. What do you think?

Also, how do I disable sorting for `dictionary` source? I hope this could make it faster.

Honestly, I don't feel like digging into performance issues of deoplete again where there is a dedicated tool that works well for this purpose. `look` does one thing and does it well and fast (unix philosophy), why replicate its functionality in slower Python?

> Because neco-look includes the other plugin sources(neocomplcache, neocomplete, deoplete).
> I don't want to touch them

Are you OK with adding this option only for deoplete?

If my comments still do no persuade you, I'm totally fine with adding the option myself in my own fork, no problems with that (though I wish I didn't have to do that as having multiple forks of a good tool is confusing to me...).

**Comment by balta2ar** [comment]
I did this:
``` vim
call deoplete#custom#set('dictionary', 'matchers', ['matcher_head'])
call deoplete#custom#set('dictionary', 'sorters', [])
```
and there is still a slight delay before the menu pops up...

**Comment by Shougo** [comment]
@balta2ar You should set min_pattern_length option.
neco-look uses it.

**Comment by Shougo** [comment]
You can create PR like this.
https://github.com/ujihisa/neco-look/pull/17

I will check your PR.

> Additionally, it could be nice to have an option for look's --ignore-case argument.

You can create the PR.

**Comment by Shougo** [comment]
>  If not, I think there could be a special mode to lookup words from dictionary using binary search. What do you think?

It cannot.  To use binary search, it must be sorted.
And it is not for fuzzy search.

**Comment by balta2ar** [comment]
> You can create the PR.

OK, I'll try to come up with something.

> It cannot. To use binary search, it must be sorted.
> And it is not for fuzzy search.

You can read the dictionary and sort it once, and then always use binary search.
Yes, this isn't fuzzy, but sometimes fuzzy is not necessary. This case, when you're looking up words from a dictionary, is one of them. I suspect "matcher_head" might be doing similar things...

**Comment by Shougo** [comment]
> I suspect "matcher_head" might be doing similar things...

matcher_head is not only for dictionary.
If the candidates are changed, your solution cannot be used.
Yes, the dictionary is fixed, you can do it.
