### ISSUE TITLE
Turn off feature real time

### ISSUE THREAD

**Issue by mangkokoo** [ujihisa/neco-look#22]
Hi developers, Can I turn off the feature for temporarily in realtime(like toggle on off)? because it gets distracting when you don't want to use it. Thanks

**Comment by Shougo** [comment]
It depends on your auto completion plugin.
What plugin do you use?

**Comment by mangkokoo** [comment]
I use deoplete Shougo, best completer

**Comment by ujihisa** [comment]
deoplete is amazing :+1:

**Comment by mangkokoo** [comment]
I use somehing like 

let b:deoplete_ignore_sources = ['look']

but it doesn't work? how do I turn off this? thanks
