### ISSUE TITLE
Selective loading of plugin not working

### ISSUE THREAD

**Issue by dky** [ujihisa/neco-look#24]
Hello, thank you for this plugin, it's useful during writing. As such I want to only load this when editing markdown files so I attempted to use:

Plug 'ujihisa/neco-look', { 'for': 'markdown' }

However it's not selectively loading it appears to be loading for all file types. Even when I use a python file I see snippets starting with [look] for expansion. Any idea how to turn this on only for markdown files? Copy of my vim file is here for reference:

https://github.com/dky/dotfiles/blob/master/.vimrc

**Comment by Shougo** [comment]
`call deoplete#custom#source('look', 'filetypes', ['markdown'])`

**Comment by dky** [comment]
Thank you @Shougo, this is now working!
