### ISSUE TITLE
`.` does not work if filetype is sh

### ISSUE THREAD

**Issue by e-kwsm** [ujihisa/neco-look#25]
## Environment

- neovim/neovim@e0a4399adc4472b9b02a26c7f93b056c4725a6b9
- Python: 3.7.3
- neco-look: 4d7f1fd7e406c302fba2a1358017c5a76d0f9fc1
- Shougo/deoplete.nvim@0901b1886208a32880b92f22bf8f38a17e95045a
- pynvim: 0.4.2

## Minimum vimrc:

```vim
set runtimepath-=~/.config/nvim
set runtimepath-=~/.config/nvim/after
set runtimepath-=~/.local/share/nvim/site
set runtimepath-=~/.local/share/nvim/site/after
set runtimepath+=/path/to/deoplete.nvim
set runtimepath+=/path/to/neco-look
let g:deoplete#enable_at_startup = 1
```

## How to Reproduce
```sh
nvim -u vimrc -c 'setf sh' << EOF
XDG_CONFIG_HOME
XDG_CONFIG_HOME
EOF
```

1. `ceprefix<ESC>`
2. `<CR>.`

Expected:
```
prefix
prefix
```

Actual:
```
prefix
xXDG_CONFIG_HOME
```

**Comment by e-kwsm** [comment]
If filetype is not `sh` (e.g., `c`, `python`) or not set, `.` works correctly.

**Comment by Shougo** [comment]
I don't think it is neco-look related problem.
Why did you created it in neco-look issues?

**Comment by Shougo** [comment]
Reproduced.  It is deoplete bug.

**Comment by Shougo** [comment]
Fixed.  Please use the latest of deoplete.

**Comment by e-kwsm** [comment]
Thanks.
